#!/bin/bash
set -e

CMD_PATH=/usr/bin/python
INSTALL_PATH="$( cd "$( dirname "$BASH_SOURCE" )" && pwd -P )"/venv
PRIORITY=2
REPO=ppa:deadsnakes/ppa

install_pip() {
	sudo apt install python3-pip
	sudo pip3 install virtualenv
}

install_python() { # install_python ${python_version}
	msg "version: $1"
	msg "venv Name: $1"
	msg "=================="
	msg "install python$1"
	msg "=================="
	sudo apt install python$1 python$1-dev
}

msg() {
	echo $1
}

python3_def() {
	sudo update-alternatives --install ${CMD_PATH} python ${CMD_PATH}/python$1 PRIORITY
	sudo update-alternatives --config python
}

set_virenv() { # set_virenv ${python_version} ${venv_name}
	cd ${INSTALL_PATH}
	if [ -z "$(ls | grep $2)" ]; then
		msg "=================="
		msg "create virtual env"
		msg "=================="
		virtualenv $2 --python=$1 --system-site-package
		echo $(ls -d */) > venvlist
	else
		msg "already exist venv name"
		echo $(ls -d */) > ${INSTALL_PATH}/venvlist
	fi
	msg "===== complete create virtualenv ====="
	cd ${PWD}
}

update_repository() {
	sudo add-apt-repository ${REPO}
	sudo apt-get update
}
