#!/bin/bash
set -e

INSTALL_PATH="$( cd "$( dirname "$BASH_SOURCE" )" && pwd -P )"/venv
PRIORITY=2
PYTHON_CMD_PATH=/usr/bin/python
PYTHON3_CMD_PATH=/usr/bin/python3
REPO=ppa:deadsnakes/ppa

install_pip() {
	sudo apt install python3-pip
	sudo pip3 install virtualenv
}

install_python() { # install_python ${python_version}
	msg "version: $1"
	msg "venv Name: $1"
	msg "=================="
	msg "install python$1"
	msg "=================="
	sudo apt install python$1 python$1-dev
}

msg() {
	echo $1
}

python_def() {
	sudo update-alternatives --install ${PYTHON_CMD_PATH} python \
		${PYTHON_CMD_PATH}$1 ${PRIORITY}
	sudo update-alternatives --config python
}

python_remove() {
	sudo update-alternatives --remove python ${PYTHON_CMD_PATH}$1
	sudo update-alternatives --list
}

python3_def() {
	sudo update-alternatives --install ${PYTHON3_CMD_PATH} python3 \
		${PYTHON_CMD_PATH}$1 ${PRIORITY}
	sudo update-alternatives --config python3
}

python3_remove() {
	sudo update-alternatives --remove python3 ${PYTHON_CMD_PATH}$1
	sudo update-alternatives --list
}

set_virenv() { # set_virenv ${python_version} ${venv_name}
	cd ${INSTALL_PATH}
	if [ -z "$(ls | grep $2)" ]; then
		msg "=================="
		msg "create virtual env"
		msg "=================="
		virtualenv $2 --python=$1 --system-site-package
		echo $(ls -d */) > venvlist
	else
		msg "already exist venv name"
		echo $(ls -d */) > ${INSTALL_PATH}/venvlist
	fi
	msg "===== complete create virtualenv ====="
	cd ${PWD}
}

update_repository() {
	sudo add-apt-repository ${REPO}
	sudo apt-get update
}
